export const ROUTE_NAMES = {
  PRODUCER_LIST: 'PARTY_VIEW_COMPETITORS_TITLE',
  PRODUCER_CREATE: 'Producer Create',
  PRODUCER_DETAIL: 'Producer Detail',
  TANK_MIX_SELECTION: 'MAIN_MENU_TANK_MIX_TITLE',
  TANK_MIX_COMBINATION: 'Combinazioni',
  TANK_MIX_DETAIL: 'Dettaglio',
  TANK_MIX_ADVANCE_SEARCH: 'TANK_MIX_HOME_ADVANCED_SEARCH',
};
