variables:
  CUSTOMER_NAME: valagro
  IMAGE_TAG: "$REGISTRY_ACCOUNT/$CI_PROJECT_PATH_SLUG-$CUSTOMER_NAME:$CI_PIPELINE_IID"
  IMAGE_TAG_REF: "$REGISTRY_ACCOUNT/$CI_PROJECT_PATH_SLUG-$CUSTOMER_NAME:$CI_COMMIT_REF_NAME"
  IMAGE_TAG_LATEST: "$REGISTRY_ACCOUNT/$CI_PROJECT_PATH_SLUG-$CUSTOMER_NAME:latest"
  IMAGE_TAG_MASTER: "$REGISTRY_ACCOUNT/$CI_PROJECT_PATH_SLUG-$CUSTOMER_NAME:master"

stages:
  - docker image

.docker-build:
  stage: docker image
  image: docker:18-git
  services:
    - name: docker:18.09.7-dind
  before_script:
    - docker login -u $REGISTRY_ACCOUNT -p $REGISTRY_PASSWORD 
  script: &default_script_docker
    - echo Building ${IMAGE_TAG}

docker_build_tag_latest:
  extends: .docker-build
  script:
    - *default_script_docker
    - docker build --build-arg customer=$CUSTOMER_NAME -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $IMAGE_TAG_REF
    - docker tag $IMAGE_TAG $IMAGE_TAG_LATEST
    - docker push $IMAGE_TAG_REF
    - docker push $IMAGE_TAG_LATEST
  only:
    - tags

docker_build_master:
  extends: .docker-build
  script:
    - *default_script_docker
    - docker build --build-arg customer=$CUSTOMER_NAME -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $IMAGE_TAG_MASTER
    - docker push $IMAGE_TAG_MASTER
  only:
    - master

docker_build_branches:
  extends: .docker-build
  script:
    - *default_script_docker
    - CORRECTED_IMAGE_TAG_REF="$REGISTRY_ACCOUNT/$CI_PROJECT_PATH_SLUG:$(echo $CI_COMMIT_REF_NAME | tr / _)"
    - docker build --build-arg customer=$CUSTOMER_NAME -t $CORRECTED_IMAGE_TAG_REF .
    - docker push $CORRECTED_IMAGE_TAG_REF
  only:
    - branches
  except:
    - master
